### ISSUE TITLE
Style missing

### ISSUE THREAD

**Issue by Berkmann18** [contentco/quill-emoji#100]
I seem to get it working on `vue-quill-editor` however the style of the emoji selector seems fucked-up.

![image](https://user-images.githubusercontent.com/8260834/77688719-73660780-6f98-11ea-8ce0-361f2534e536.png)

Is it normal?

**Comment by castroCrea** [comment]
add `import "quill-emoji/dist/quill-emoji.css";`

**Comment by Berkmann18** [comment]
@castroCrea Thanks.

**Comment by amit1rrr** [comment]
> add `import "quill-emoji/dist/quill-emoji.css";`

I had the same styling issue as OP. When I import the CSS then styling starts working but somehow all the emojis are gone.

Any ideas?


**With CSS import -**
![Screenshot 2020-08-31 at 12 06 52 PM](https://user-images.githubusercontent.com/1350490/91689819-7a65f700-eb82-11ea-8a6e-a7d8e9a1bd21.png)


**Without CSS import**
![Screenshot 2020-08-31 at 12 04 35 PM](https://user-images.githubusercontent.com/1350490/91689685-412d8700-eb82-11ea-83f2-06ead9981360.png)

**Comment by amit1rrr** [comment]
Funnily enough, all the emojis are available when I look at chrome console but just aren't visible. I looked at all the styles and nothing is hiding it as such so I'm not sure what's happening.



![Screenshot 2020-08-31 at 12 37 21 PM](https://user-images.githubusercontent.com/1350490/91692567-33c6cb80-eb87-11ea-92ab-c4ac31e17491.png)

**Comment by bochen-dev** [comment]
> Funnily enough, all the emojis are available when I look at chrome console but just aren't visible. I looked at all the styles and nothing is hiding it as such so I'm not sure what's happening (screenshot 2).
> 
> Typing the text also shows emoji text but not the actual rendered emoji (screenshot 1).
> 
> ![Screenshot 2020-08-31 at 12 42 04 PM](https://user-images.githubusercontent.com/1350490/91692744-83a59280-eb87-11ea-8577-555b1e566cee.png)
> 
> ![Screenshot 2020-08-31 at 12 37 21 PM](https://user-images.githubusercontent.com/1350490/91692567-33c6cb80-eb87-11ea-92ab-c4ac31e17491.png)

Add `esModule: false` to your `url-loader` options

```
{
  test: /\.(png|jpe?g|gif)(\?.*)?$/,
  loader: 'url-loader',
  options: {
    name: utils.assetsPath('img/[name].[hash:7].[ext]'),
    esModule: false  // <---
  }
},
```
