### ISSUE TITLE
use quill-emoji through vue-quill-editor webpack report error

### ISSUE THREAD

**Issue by fanjiangwei7** [contentco/quill-emoji#11]
I use the quill-emoji through the vue-quill-editor. and when the webpack run , it always get the error link this.
![image](https://user-images.githubusercontent.com/17830397/33759355-f6c0cfb2-dc3c-11e7-9a13-9412334835c1.png)
I do not know why the components can not find the Quill.

**Comment by michaelbukachi** [comment]
I'm still getting this error. Any particular fix for this?
