### ISSUE TITLE
how to config it ?

### ISSUE THREAD

**Issue by zzzgit** [contentco/quill-emoji#15]
![image](https://i.imgur.com/nEYpMzV.png)

I configed it following the documentation, and then got an error

**Comment by EsmeraldiBejolli** [comment]
@zzzgit did u fix this error

**Comment by zzzgit** [comment]
no i didn't and i gave up squill
i am waiting for the next main version of squill

**Comment by klaslundberg** [comment]
@zzzgit @EsmeraldiBejolli Documentation has been updated to reflect the latest release v0.1.2
