### ISSUE TITLE
Autocomplete not working on Firefox

### ISSUE THREAD

**Issue by cedricium** [contentco/quill-emoji#21]
I'm making an application that uses `quill-emoji` and I specifically only want the autocomplete using the `:` character to work (no emoji toolbar). Using the instructions outlined in the `demo` repo, I've been able to get this working for Chrome, however, the same steps / code **does not work on Firefox.** No matter what, using colon never brings up emojis.

Has anyone ran into this and / or have a solution?

**Comment by klaslundberg** [comment]
Yep, the wrong keycode is registered for the shortcut. There is a fix in PR #23 Commit https://github.com/contentco/quill-emoji/pull/23/commits/9d5d0cf7076e0a5cf7a1b72a733744ebd60d315f

**Comment by cwhite-connectfirst** [comment]
Closing this issue now, since I've verified that autocomplete works in the example app (in `demo/index.html`) while running with Firefox.
