### ISSUE TITLE
How to use unicode emojis?

### ISSUE THREAD

**Issue by Theo38** [contentco/quill-emoji#25]
Hi there.

After some hours to configurate it, I'm looking to send datas to the base. For this, I can not use the img tag and I've not been able to change the img to another thing. The format-emoji-blot seems invisible.

I have seen in the list that emojis got unicode, so, I'm wondering, how can we use it?

Thanks,

**Comment by Theo38** [comment]
Well. Without support I finally used a span instead of img by changing dist/quill-emoji.js tag name and a regex to transform span to img. 
Smthg similar to 

$text = '<span class="emoji ap ap-kissing_closed_eyes" src="data:image/png;base64,R0lGODlhAQABAAAAACwAAAAAAQABAAA="><span contenteditable="false"></span>﻿</span>';
$regex = '%^(<span class="(.*?)" src="data:image/png;base64,R0lGODlhAQABAAAAACwAAAAAAQABAAA=">(.*?)</span>)$%';
$replace = '<img class="$2" src="data:image/png;base64,R0lGODlhAQABAAAAACwAAAAAAQABAAA=">';
echo preg_replace($regex, $replace, $text);

Hard solution, but it works.

**Comment by klaslundberg** [comment]
@Theo38 You should be able to create a custom emoji-blot to add any properties you want. See #13
