### ISSUE TITLE
Publish latest release to NPM?

### ISSUE THREAD

**Issue by cwhite-connectfirst** [contentco/quill-emoji#28]
Hey guys,

First off, thanks for putting this project together. It's been a huge help. Second, are you guys planning on publishing the latest changes (https://github.com/contentco/quill-emoji/commit/2ff9f4e0ff06ccb964408c8661167f3f35ef5209) to NPM? I think the hosted version they have there is still on v0.0.9.

**Comment by klaslundberg** [comment]
@cwhite-connectfirst v.0.1.2 should be available on npm now 

https://www.npmjs.com/package/quill-emoji
