### ISSUE TITLE
When using webpack (via laravel-mix) 404 for sprite sheet

### ISSUE THREAD

**Issue by robertdrakedennis** [contentco/quill-emoji#30]
`GET http://xenin.local/Users/tim/contentco/quill-emoji/dist/1e7b63404cd2fb8e6525b2fd4ee4d286.png 404 (Not Found)`

Sass compiles without errors, copies images over but still uses this url.

**Comment by klaslundberg** [comment]
@robertdrakedennis This should be resolved in v.0.1.2
