### ISSUE TITLE
Convert quill-emoji to html

### ISSUE THREAD

**Issue by PostMidnight** [contentco/quill-emoji#37]
Hello,
I am new to this project so kindly excuse my complete ignorance.
I am trying to integrate quill into a forum, To that end I need to render quill's delta without an editor.
I tried using quill-delta-to-html but the output of the converter is empty (when it hits emoji).
Is there something I am doing wrong?
Thank you in advance!
JJ.

**Comment by PostMidnight** [comment]
looking good, thank you!

**Comment by c0bra** [comment]
@PostMidnight did it work for you after updating or did you have to do something else?  I'm experiencing your issue with version 0.1.7.

**Comment by PostMidnight** [comment]
Hi @c0bra , the new emoji works well. Quill however may need further work. See the quill page for documented issues and potential solutions.

**Comment by PostMidnight** [comment]
Hi @c0bra it did work for me, however take a look at the quill page there may be some other issues related to yours.

**Comment by c0bra** [comment]
So I had to go another route. I forked this repo and exported `emoji-map.js` as a named export.

Then I used the map to convert emoji names to unicode characters like so:

```
import { EmojiMap } from 'quill-emoji';

const emoji = 'smile';
const code = String.fromCodePoint(parseInt(EmojiMap[emoji].unicode, 16));
```

**Comment by kembly** [comment]
> So I had to go another route. I forked this repo and exported `emoji-map.js` as a named export.
> 
> Then I used the map to convert emoji names to unicode characters like so:
> 
> ```js
> import { EmojiMap } from 'quill-emoji';
> 
> const emoji = 'smile';
> const code = String.fromCodePoint(parseInt(EmojiMap[emoji].unicode, 16));
> ```
> 
> This has worked for me in sending SMS content, etc.

@c0bra, you can actually just get it from this package without forking: https://github.com/contentco/quill-emoji/blob/master/src/module-emoji.js

```
import QuillEmoji from 'quill-emoji';
const { EmojiBlot, ShortNameEmoji, ToolbarEmoji } = QuillEmoji;
console.log(ShortNameEmoji.DEFAULTS.emojiList);
```
