### ISSUE TITLE
Thumbsup emoji shows wrongly

### ISSUE THREAD

**Issue by jrvaja** [contentco/quill-emoji#38]
@olsgreen @cbracco @himynameistimli @klaslundberg @vloginov 
Hey Team,

I really love this extension for Quill.
It seems that thumbsup is not showing correct emoji.

![screen shot 2018-10-12 at 11 39 34 am](https://user-images.githubusercontent.com/1858318/46851047-cd5e2600-ce13-11e8-9366-697827a44268.png)

Can you please let me know if I am missing something?
Regards,

**Comment by CFT-Chris** [comment]
Should be fixed now with #57
