### ISSUE TITLE
Emoji shortname module is working in Chrome, but not Firefox

### ISSUE THREAD

**Issue by cwhite-connectfirst** [contentco/quill-emoji#43]
The autocomplete module for emojis doesn't appear in firefox when a user types in a partial emoji name. See the following gif from firefox:
https://gyazo.com/78e2c5841a1b5d6949493fa805021ebf

Here's the working version in chrome:
https://gyazo.com/b6df04b272a49fbd77129ad5dcae1da1

Both of those gifs were generated from https://github.com/contentco/quill-emoji/blob/master/demo/index.html. I'm running MacOS High Sierra v10.13.6, chrome v69.0.3497.100, and firefox v62.0.3.

Let me know if there's anything else I can provide that might be of help to you guys. Also, I'll post anything else I learn about this issue here. Thanks again for keeping this project running, it's been a huge help.

**Comment by cwhite-connectfirst** [comment]
I think I got it. The semicolon keycode in gecko based browsers is 59 ([see here](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode)), and there was no binding added for that keycode.

**Comment by cwhite-connectfirst** [comment]
Confirmed that this issue has been resolved in the demo.

**Comment by pmaddaloni-shujinko** [comment]
This appears to be broken again in FF :(
