### ISSUE TITLE
Cursor disappears after the emoji

### ISSUE THREAD

**Issue by sebastian-walter** [contentco/quill-emoji#49]
Hi there,

I encountered the problem that after inserting the emoji the cursor disappears. The cursor appears again when I hit space. The cursor disappears again when I am putting the cursor right in front of the emoji (see gif)
![ezgif com-video-to-gif 4](https://user-images.githubusercontent.com/15271363/47729442-730cf400-dc60-11e8-8289-95655b8f1731.gif)

**Comment by CFT-Chris** [comment]
Fixed with #59
