### ISSUE TITLE
../../sheet_apple_64.png in ./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./node_modules/quill-emoji/src/scss/quill-emoji.scss

### ISSUE THREAD

**Issue by Abo-Hani** [contentco/quill-emoji#56]
I started facing this error after I have imported the package via NPM. My package is: 

`"devDependencies": {
        "axios": "^0.18.0",
        "bootstrap": "^4.0.0",
        "cross-env": "^5.1",
        "css-loader": "^1.0.1",
        "jquery": "^3.2",
        "laravel-mix": "^2.0",
        "less": "^2.3.1",
        "less-loader": "^4.1.0",
        "lodash": "^4.17.5",
        "node-sass": "^4.10.0",
        "popper.js": "^1.12",
        "quill-image-drop-module": "^1.0.3",
        "quill-image-extend-module": "^1.1.2",
        "quill-image-resize-module": "^3.0.0",
        "sass-loader": "^7.1.0",
        "resolve-url-loader": "^3.0.0",
        "style-loader": "^0.23.1",
        "stylus": "^0.54.5",
        "stylus-loader": "^3.0.2",
        "vue": "^2.5.17",
        "vue-html5-editor": "^1.1.1"
    },`

**Comment by CFT-Chris** [comment]
PR #53 fixes this.

**Comment by CFT-Chris** [comment]
@vishnup10 I don't think the path is the issue. Logically the path is correct as the png file is two subfolders down. The relative path should be agnostic of what file imports or includes it.

The addition of the leading '/' to make the path ``/../../sheet_apple_64.png`` in your PR suggests to look two subfolders under the base subfolder, which doesn't make sense to me.

Please take a look at [this comment](https://github.com/contentco/quill-emoji/issues/47#issuecomment-440773423) in the duplicate issue to see if you are missing the ``resolve-url-loader`` in your webpack.config.

Ideally you don't need to include the scss files in the src directory if you don't need to rebuild quill-emoji for your project. You can just include the pre-built dist/quill-emoji.css file in the places you want to use quill-emoji.

@himynameistimli Perhaps the best way to handle projects consuming quill-emoji (``npm i quill-emoji``) which build rules that try to include quill-emoji's **/*.scss files is to only publish the ``dist`` subfolder to npm and ignore the ``src`` folder? I can drop a PR for that.

**Comment by CFT-Chris** [comment]
#68 should fix this. In my previous comment, any projects with quill-emoji as a dependency shouldn't be importing the raw scss files and should be consuming the ``dist/quill-emoji.css`` file.

AFAIK, building the quill-emoji project from this repo works with the current relative path ([webpack.config](https://github.com/contentco/quill-emoji/blob/v0.1.6/webpack.config.js#L31) correctly has ``resolve-url-loader``) and shouldn't be changed.
