### ISSUE TITLE
Can not integrate quill-emoji into ng-quill

### ISSUE THREAD

**Issue by golovatuy** [contentco/quill-emoji#8]
I'm trying to integrate quill-emoji into ng-quill (https://www.npmjs.com/package/ng-quill), and it doesn't work. How to register module quill-emoji?

**Comment by ibudisteanu** [comment]
@golovatuy I am also struggling with importing the library for Vue.js

I tried two methods and none worked... (although, I have included before 2 other modules with success)

```
    Emoji = require('quill-emoji/dist/quill-emoji');
    Quill.register('modules/emoji', Emoji);
```

2nd method
```
   <script src="root/node_modules/quill-emoji/dist/quill-emoji.js" > </script>
```

```
editorOption: {
                    placeholder: 'Your text ...',
                    modules: {
                        toolbar: {
                            container: [
                                [{'size': ['small', false, 'large']}],
                                ['bold', 'italic', 'underline', 'strike'],                              
                                ['emoji'],
                            ],
                            handlers: {
                                'emoji': function () {}
                            },
                            toolbar_emoji: true,
                            short_name_emoji: true,
                            textarea_emoji:true
                        },
                    },
```

**Comment by michaelbukachi** [comment]
I'm getting
```
http://eslint.org/docs/rules/no-unused-vars  'Emoji' is defined but never used
src/components/SendMessage.vue:39:8
import Emoji from 'quill-emoji/dist/quill-emoji'
```
Did you face this error?

**Comment by eltimn** [comment]
@michaelbukachi in case you haven't figured it out yet. That's an eslint error. You can just import the module without naming it like this:

    import 'quill-emoji/dist/quill-emoji'

**Comment by murraybauer** [comment]
@eltimn this did not work for me.  Am I missing something.

Using your suggested `import 'quill-emoji/dist/quill-emoji'` (using latest angular CLI) gives runtime console error `Uncaught ReferenceError: Quill is not defined`  

If I remove `import 'quill-emoji/dist/quill-emoji'` all good.  

If I use `import Emoji from 'quill-emoji/dist/quill-emoji';` no console error, but does not work.

Has something changed?  The importing seems to be my error.

I have added other quill modules before and I using a blank example. But can't get `quill-emoji` to work.  My module config object is configured above in toolbar with the handler function.

**Comment by michaelbukachi** [comment]
I'm still facing the same issue as @murraybauer

**Comment by BH-NOTHING** [comment]
@murraybauer My situation is the same as you，how can you did it finally?

**Comment by eltimn** [comment]
@murraybauer it sounds like you need to include Quill itself as well. I think that has changed, but if you're using an older version like I am, quill-emoji relies on a global Quill being defined.

**Comment by osnoser1** [comment]
The answer of @ibudisteanu  works perfectly in `angular-cli` with this small variation:

```
import * as Quill from 'quill';
(window as any).Quill = Quill;
import 'quill-emoji/dist/quill-emoji';
 ```

**Comment by osnoser1** [comment]
I have the same problem @bladerunner41, but I have not had a chance to investigate. 😕

**Comment by himynameistimli** [comment]
Hey all, sorry we never got a chance to integrate this into our editor, so haven't been very good at maintaining this repo. If you would like to submit a PR to make any compatibility fixes, that would be much appreciated!

**Comment by dineshsuthar92** [comment]
@bladerunner41 I am too having same issue since 1 week and I don't know if there is way out for this problem.

**Comment by billyshena** [comment]
Any news on how to integrate quill-emoji ? Also having the same error "Quill is not defined"

**Comment by klaslundberg** [comment]
I'm using quill-emoji in a bootstrap environment with quill, so I'm not quite familiar with how to use the ng-quill. However, the current master has a few changes that makes it easier to integrate into other projects. I'm guessing you are using the latest release v0.0.7. Could someone try to integrate the latest master instead and see if there are any issues?

**Comment by klaslundberg** [comment]
ng-quill should now be working fine in v.0.1.2. See [angular.html](https://github.com/contentco/quill-emoji/blob/master/demo/angular.html) for AngularJS ng-quill example
