### ISSUE TITLE
When typing Chinese after emoji, the first letter will appear in the editor.

### ISSUE THREAD

**Issue by jeesun** [contentco/quill-emoji#83]
The problem is i what to type Chinese "你好" after emoji "😁", i hope to get "😁你好", but what i actually get is ”😁﻿n你好“.

**Comment by jeesun** [comment]
Hi contentco, i spend a whole afternoon finding what causes this bug, and finally i found that it is quill.js's code problem.What i need to do is replace '\uFEFF' to '' in quill.js.

**Comment by fred8617** [comment]
@jeesun 遇到了同样的问题，怎么解决的？
