### ISSUE TITLE
Doesn't work, nothing happens

### ISSUE THREAD

**Issue by drpiou** [contentco/quill-emoji#85]
Hi! Thanks for this plugin, I was very happy to integrate but I cannot make it works in my react code (I'm not using react-quill).

So, I just :
```
import Quill from 'quill';
import QuillEmoji from 'quill-emoji';

Quill.register('modules/emoji', QuillEmoji);

class WysiwygInputBaseComponentLib extends Base
{
	// ...

	componentWillUnmount()
	{
		this.destroyQuill();
	}

	componentDidMount()
	{
		this.initQuill();
	}

	initQuill()
	{
		const options = merge({
			// ...
			modules: {
				toolbar: {
					container: ['emoji'],
					handlers: {
						emoji: function() {},
					},
				},
				'emoji-toolbar': true,
				'emoji-textarea': false,
				'emoji-shortname': true,
			},
			// ...
		}, this.props.config);

		this.quill = new Quill(this.$editor, options);

		// ...
	}

	destroyQuill()
	{
		// Removes added events...
	}

	// ...
}
```

With that, I mean after following the small [usage procedure](https://github.com/contentco/quill-emoji#usage), it doesn't work as expected:
I can open the emoji window, but nothing is displayed (if I fix the quill-emoji css by tweaking `text-indent` and `margin-top`, I can manage something), and if I click on an emoji (visible or not after the css fix), it just doesn't show at all. The cursor position moves by +1, but nothing else.

These said, I already had a tiny pain to make this works, a better documentation would be appreciated:
- explain:
`emoji: function() {}`
`'emoji-toolbar': true`
`'emoji-textarea': false`
`'emoji-shortname': true`

- register the quill-emoji plugin
```
import Quill from 'quill';
import QuillEmoji from 'quill-emoji';
or
<script src="https://cdn.quilljs.com/1.3.5/quill.js"></script>
<script src="../dist/quill-emoji.js"></script>

Quill.register('modules/emoji', QuillEmoji);
```

- adding style:
```
@import '~quill-emoji/dist/quill-emoji.css';
or
<link rel="stylesheet" type="text/css" href="../dist/quill-emoji.css">
```

**Comment by christopheroussy** [comment]
I am not the part of this project, but I suggest you try making it work in a separate simple project using only HTML/CSS/JS/IMAGE so that you can understand how it works. The png image containing the icons must be in the same folder as the CSS based on `background-image:url(1e7b63404cd2fb8e6525b2fd4ee4d286.png);` that may be your issue. Also beware the png license, default file provided belongs to Apple/iOS, so only serve it to iOS users. Do not use emoji as part of your UI (buttons or such) as this can get you in trouble depending on the license.

**Comment by drpiou** [comment]
Okay thanks! The fact that `only serve it to iOS users` just discouraged me. I won't use this at all, it's useless for me at this, I need to serve everyone because I wanted to add this little gadget to the CMS i'm building, but I will live without that for sure without any regrets either.

**Comment by christopheroussy** [comment]
@drpiou You can find other image sheets from google and twitter with the same format (via google images or such)
